services:
  my-mysql-database:
    image: mysql:8
    container_name: my-mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: mysql-db-Lake@9691
      MYSQL_DATABASE: mycart_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      my-mysql-database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://my-mysql-database:3306/mycart_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql-db-Lake@9691

volumes:
  mysql_data:
